name: httpX
summary: httpX is a fast and multi-purpose HTTP toolkit
description: |
  httpX is a fast and multi-purpose HTTP toolkit allow to run multiple probers using retryablehttp library, it is designed to maintain the result reliability with increased threads.
version: 'v1.2.1'
icon: static/httpX-logo.png
license: AGPL 3.0
base: core18
grade: stable
confinement: strict
architectures:
  - build-on: [s390x, ppc64el, arm64, armhf and amd64]
    run-on: [s390x, ppc64el, arm64, armhf and amd64]

apps:
  httpX:
    command: bin/httpX
    plugs:
      - home
      - network
      - removable-media
      - dot-httpX

#plugs:
#  dot-httpX:
#    interface: personal-files
#    write:
#      - $HOME/.config/httpX

parts:
  httpX:
    source: https://github.com/byt3n33dl3/httpX.git
    plugin: c
    go-channel: latest/stable
